[package]
edition = "2021"
name = "xauste"
resolver = "2"
version = "0.1.0"

[dependencies]
hard-xml = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
ureq = { version = "2", features = ["cookies"] }

[profile.release]
lto = "fat"
